### ISSUE TITLE
Facebook API / Image rendering API

### ISSUE THREAD

**Issue by tomtom828** [tomtom28/bucketBuddiez#2]
I'm not sure if the Facebook API will be client side or sever-side. It's in client side, we can put your API calls into the `public/assets/javascript` folder. Otherwise, I guess we can make a custom server-side folder or put it in the `controllers` folder for now.

The same goes for the image API. I'm guessing we could take 2 paths...
  1) a one time query to find an image link and save it to the database.
  2) or search a country name in the api and append it to the right tile in the DOM

Not sure which will be simpler at this point.

**Comment by marioaburto10** [comment]
As of now it's going to be client side and I put it in `public/login.html`
